import palettable

PALETTES = {
    'palettable.cartocolors.diverging': [
        palettable.cartocolors.diverging.ArmyRose_7,
        palettable.cartocolors.diverging.Earth_7,
        palettable.cartocolors.diverging.Fall_7,
        palettable.cartocolors.diverging.Geyser_7,
        palettable.cartocolors.diverging.TealRose_7,
        palettable.cartocolors.diverging.Temps_7,
        palettable.cartocolors.diverging.Tropic_7,
    ],
    'palettable.cartocolors.qualitative': [
        palettable.cartocolors.qualitative.Antique_10,
        palettable.cartocolors.qualitative.Bold_10,
        palettable.cartocolors.qualitative.Pastel_10,
        palettable.cartocolors.qualitative.Prism_10,
        palettable.cartocolors.qualitative.Safe_10,
        palettable.cartocolors.qualitative.Vivid_10,
    ],
    'palettable.cartocolors.sequential': [
        palettable.cartocolors.sequential.BluGrn_7,
        palettable.cartocolors.sequential.BluYl_7,
        palettable.cartocolors.sequential.BrwnYl_7,
        palettable.cartocolors.sequential.Burg_7,
        palettable.cartocolors.sequential.BurgYl_7,
        palettable.cartocolors.sequential.DarkMint_7,
        palettable.cartocolors.sequential.Emrld_7,
        palettable.cartocolors.sequential.Magenta_7,
        palettable.cartocolors.sequential.Mint_7,
        palettable.cartocolors.sequential.OrYel_7,
        palettable.cartocolors.sequential.Peach_7,
        palettable.cartocolors.sequential.PinkYl_7,
        palettable.cartocolors.sequential.Purp_7,
        palettable.cartocolors.sequential.PurpOr_7,
        palettable.cartocolors.sequential.RedOr_7,
        palettable.cartocolors.sequential.Sunset_7,
        palettable.cartocolors.sequential.SunsetDark_7,
        palettable.cartocolors.sequential.Teal_7,
        palettable.cartocolors.sequential.TealGrn_7,
        palettable.cartocolors.sequential.agGrnYl_7,
        palettable.cartocolors.sequential.agSunset_7
    ],
    'palettable.colorbrewer.diverging': [
        palettable.colorbrewer.diverging.BrBG_11,
        palettable.colorbrewer.diverging.PRGn_11,
        palettable.colorbrewer.diverging.PiYG_11,
        palettable.colorbrewer.diverging.PuOr_11,
        palettable.colorbrewer.diverging.RdBu_11,
        palettable.colorbrewer.diverging.RdGy_11,
        palettable.colorbrewer.diverging.RdYlBu_11,
        palettable.colorbrewer.diverging.RdYlGn_11,
        palettable.colorbrewer.diverging.Spectral_11,
    ],
    'palettable.colorbrewer.sequential': [
        palettable.colorbrewer.sequential.Blues_9,
        palettable.colorbrewer.sequential.BuGn_9,
        palettable.colorbrewer.sequential.BuPu_9,
        palettable.colorbrewer.sequential.GnBu_9,
        palettable.colorbrewer.sequential.Greens_9,
        palettable.colorbrewer.sequential.Greys_9,
        palettable.colorbrewer.sequential.OrRd_9,
        palettable.colorbrewer.sequential.Oranges_9,
        palettable.colorbrewer.sequential.PuBuGn_9,
        palettable.colorbrewer.sequential.PuBu_9,
        palettable.colorbrewer.sequential.PuRd_9,
        palettable.colorbrewer.sequential.Purples_9,
        palettable.colorbrewer.sequential.RdPu_9,
        palettable.colorbrewer.sequential.Reds_9,
        palettable.colorbrewer.sequential.YlGnBu_9,
        palettable.colorbrewer.sequential.YlGn_9,
        palettable.colorbrewer.sequential.YlOrBr_9,
        palettable.colorbrewer.sequential.YlOrRd_9
    ],
    'palettable.colorbrewer.qualitative': [
        palettable.colorbrewer.qualitative.Accent_8,
        palettable.colorbrewer.qualitative.Dark2_8,
        palettable.colorbrewer.qualitative.Paired_12,
        palettable.colorbrewer.qualitative.Pastel2_8,
        palettable.colorbrewer.qualitative.Set1_9,
        palettable.colorbrewer.qualitative.Set2_8,
        palettable.colorbrewer.qualitative.Set3_12,
    ],
    'palettable.cmocean.diverging': [
        # Using 9 colours only as otherwise there's too many
        palettable.cmocean.diverging.Balance_9,
        palettable.cmocean.diverging.Curl_9,
        palettable.cmocean.diverging.Delta_9,
    ],
    'palettable.cmocean.sequential': [
        # Using 9 colours only as otherwise there's too many
        palettable.cmocean.sequential.Algae_9,
        palettable.cmocean.sequential.Amp_9,
        palettable.cmocean.sequential.Deep_9,
        palettable.cmocean.sequential.Dense_9,
        palettable.cmocean.sequential.Gray_9,
        palettable.cmocean.sequential.Haline_9,
        palettable.cmocean.sequential.Ice_9,
        palettable.cmocean.sequential.Matter_9,
        palettable.cmocean.sequential.Oxy_9,
        palettable.cmocean.sequential.Phase_9,
        palettable.cmocean.sequential.Solar_9,
        palettable.cmocean.sequential.Speed_9,
        palettable.cmocean.sequential.Tempo_9,
        palettable.cmocean.sequential.Thermal_9,
        palettable.cmocean.sequential.Turbid_9,
    ],
    'palettable.lightbartlein.diverging': [
        palettable.lightbartlein.diverging.BlueDarkOrange12_9,
        palettable.lightbartlein.diverging.BlueDarkOrange18_9,
        palettable.lightbartlein.diverging.BlueDarkRed12_9,
        palettable.lightbartlein.diverging.BlueDarkRed18_9,
        palettable.lightbartlein.diverging.BlueGreen_9,
        palettable.lightbartlein.diverging.BlueOrange10_9,
        palettable.lightbartlein.diverging.BlueOrange12_9,
        palettable.lightbartlein.diverging.BlueOrangeRed_9,
        palettable.lightbartlein.diverging.BrownBlue10_9,
        palettable.lightbartlein.diverging.BrownBlue12_9,
        palettable.lightbartlein.diverging.GreenMagenta_9,
        palettable.lightbartlein.diverging.RedYellowBlue_9
    ],
    'palettable.lightbartlein.sequential': [
        palettable.lightbartlein.sequential.Blues10_7,
        palettable.lightbartlein.sequential.Blues7_7
    ],
    'palettable.matplotlib': [
        palettable.matplotlib.Inferno_9,
        palettable.matplotlib.Magma_9,
        palettable.matplotlib.Plasma_9,
        palettable.matplotlib.Viridis_9
    ],
    'palettable.mycarta': [
        palettable.mycarta.Cube1_9,
        palettable.mycarta.CubeYF_9,
        palettable.mycarta.LinearL_9
    ],
    'palettable.scientific.diverging': [
        palettable.scientific.diverging.Berlin_9,
        palettable.scientific.diverging.Broc_9,
        palettable.scientific.diverging.Cork_9,
        palettable.scientific.diverging.Lisbon_9,
        palettable.scientific.diverging.Roma_9,
        palettable.scientific.diverging.Tofino_9,
        palettable.scientific.diverging.Vik_9
    ],
    'palettable.scientific.sequential': [
        palettable.scientific.sequential.Acton_9,
        palettable.scientific.sequential.Bamako_9,
        palettable.scientific.sequential.Batlow_9,
        palettable.scientific.sequential.Bilbao_9,
        palettable.scientific.sequential.Buda_9,
        palettable.scientific.sequential.Davos_9,
        palettable.scientific.sequential.Devon_9,
        palettable.scientific.sequential.GrayC_9,
        palettable.scientific.sequential.Hawaii_9,
        palettable.scientific.sequential.Imola_9,
        palettable.scientific.sequential.LaJolla_9,
        palettable.scientific.sequential.LaPaz_9,
        palettable.scientific.sequential.Nuuk_9,
        palettable.scientific.sequential.Oleron_9,
        palettable.scientific.sequential.Oslo_9,
        palettable.scientific.sequential.Tokyo_9,
        palettable.scientific.sequential.Turku_9
    ],
    'palettable.tableau': [
        palettable.tableau.BlueRed_6,
        palettable.tableau.BlueRed_12,
        palettable.tableau.ColorBlind_10,
        palettable.tableau.Gray_5,
        palettable.tableau.GreenOrange_12,
        palettable.tableau.PurpleGray_6,
        palettable.tableau.PurpleGray_12,
        palettable.tableau.Tableau_10,
        palettable.tableau.Tableau_20,
        palettable.tableau.TableauLight_10,
        palettable.tableau.TableauMedium_10,
        palettable.tableau.TrafficLight_9,
    ],
    'palettable.wesanderson': [
        palettable.wesanderson.Aquatic1_5,
        palettable.wesanderson.Aquatic2_5,
        palettable.wesanderson.Aquatic3_5,
        palettable.wesanderson.Cavalcanti_5,
        palettable.wesanderson.Chevalier_4,
        palettable.wesanderson.Darjeeling1_4,
        palettable.wesanderson.Darjeeling2_5,
        palettable.wesanderson.Darjeeling3_5,
        palettable.wesanderson.Darjeeling4_5,
        palettable.wesanderson.FantasticFox1_5,
        palettable.wesanderson.FantasticFox2_5,
        palettable.wesanderson.GrandBudapest1_4,
        palettable.wesanderson.GrandBudapest2_4,
        palettable.wesanderson.GrandBudapest3_6,
        palettable.wesanderson.GrandBudapest4_5,
        palettable.wesanderson.GrandBudapest5_5,
        palettable.wesanderson.IsleOfDogs1_5,
        palettable.wesanderson.IsleOfDogs2_6,
        palettable.wesanderson.IsleOfDogs3_4,
        palettable.wesanderson.Margot1_5,
        palettable.wesanderson.Margot2_4,
        palettable.wesanderson.Margot3_4,
        palettable.wesanderson.Mendl_4,
        palettable.wesanderson.Moonrise1_5,
        palettable.wesanderson.Moonrise2_4,
        palettable.wesanderson.Moonrise3_4,
        palettable.wesanderson.Moonrise4_5,
        palettable.wesanderson.Moonrise5_6,
        palettable.wesanderson.Moonrise6_5,
        palettable.wesanderson.Moonrise7_5,
        palettable.wesanderson.Royal1_4,
        palettable.wesanderson.Royal2_5,
        palettable.wesanderson.Royal3_5,
        palettable.wesanderson.Zissou_5,
    ]
}
